POST http://54.86.161.133:5005/webhooks/rest/webhook HTTP/1.1
Content-Type: application/json


{
     "sender": "user_s",
    "message": "Hola"
}

###

POST http://localhost:5005/webhooks/rest/webhook HTTP/1.1
Content-Type: application/json


{
    "sender": "user_s",
    "message": "Quisiera agendar una cita"
}




### 

POST http://localhost:5005/webhooks/rest/webhook HTTP/1.1
Content-Type: application/json


{
    "sender": "user_s",
    "message": "Mi numero de identificacion es 1214746404"
}


###

POST http://localhost:5005/webhooks/rest/webhook HTTP/1.1
Content-Type: application/json


{
     "sender": "user_s",
    "message": "enero"
}


###

POST http://localhost:5005/webhooks/rest/webhook HTTP/1.1
Content-Type: application/json


{
     "sender": "user_s",
    "message": "Estaria  bien el 25"
}


###

POST http://localhost:5005/webhooks/rest/webhook HTTP/1.1
Content-Type: application/json


{
     "sender": "user_s",
    "message": "1:30 de la tarde"
}




###
POST http://7gqvd.mocklab.io/rasa HTTP/1.1
Content-Type: application/json


{

    "dni":1214746404

}



###
POST http://localhost:5005/webhooks/rest/webhook HTTP/1.1
Content-Type: application/json


{
     "sender": "user_s",
    "message": "Puedes darme la cita mas cercana posible porfavor"
}



###
POST https://appointments-carvajal.herokuapp.com/appointments HTTP/1.1
Content-Type: application/json


{
    "name_user": "Ricardo",
    "appointment_type": "Cita Medica",
    "appoinment_with": "Carlos",
    "datetime": "2021-05-19T00:00:00.000Z",
    "hours": [{"client_name": "Alberto","available":true,  "time":"00:30:00"} ]
}


###
POST http://localhost:5005/webhooks/rest/webhook HTTP/1.1
Content-Type: application/json;charset=utf-8


{
     "sender": "user_s",
    "message": "Puedes decirme la disponibilidad de las citas del 25 de enero"
}


###
GET https://appointments-carvajal.herokuapp.com/appointments HTTP/1.1
Content-Type: application/json

