POST http://localhost:5005/webhooks/rest/webhook HTTP/1.1
Content-Type: application/json


{
     "sender": "user_s",
    "message": "Hola"
}

###

POST http://localhost:5005/webhooks/rest/webhook HTTP/1.1
Content-Type: application/json


{
    "sender": "user_s",
    "message": "Quisiera agendar una cita"
}




### 

POST http://localhost:5005/webhooks/rest/webhook HTTP/1.1
Content-Type: application/json


{
    "sender": "user_s",
    "message": "Mi numero de identificacion es 1214746404"
}


###

POST http://localhost:5005/webhooks/rest/webhook HTTP/1.1
Content-Type: application/json


{
     "sender": "user_s",
    "message": "Enero"
}


###

POST http://localhost:5005/webhooks/rest/webhook HTTP/1.1
Content-Type: application/json


{
     "sender": "user_s",
    "message": "Martes"
}


###

POST http://localhost:5005/webhooks/rest/webhook HTTP/1.1
Content-Type: application/json


{
     "sender": "user_s",
    "message": "1 de la tarde"
}




###
POST http://7gqvd.mocklab.io/rasa HTTP/1.1
Content-Type: application/json


{

    "dni":1214746404

}



###
POST http://localhost:5005/webhooks/rest/webhook HTTP/1.1
Content-Type: application/json


{
     "sender": "user_s",
    "message": "Puedes darme la cita mas cercana posible porfavor"
}
